#!/data/spirou/venv/bin/python3 -u

import datetime

from drsloader import DrsLoader
from logger import configure_logger
from offline_trigger import get_base_argument_parser, reduce_execute
from realtime import load_and_start_realtime, run_listener

if __name__ == '__main__':
    parser, subparsers = get_base_argument_parser(additional_step_options=['distribute', 'database', 'distraw'])
    parser.add_argument('--config', help='Use custom DRS config directory')
    version_parse = subparsers.add_parser('version', help='DRS version information')
    version_flags = version_parse.add_mutually_exclusive_group(required=False)
    version_flags.add_argument('--drs', action='store_true')
    version_flags.add_argument('--trigger', action='store_true')
    realtime_parse = subparsers.add_parser('realtime', aliases=['listener'],
                                           help='Reduce files from observing session and update DB')
    realtime_parse.add_argument('--port', type=int, default=9998)
    realtime_parse.add_argument('--processes', type=int, default=6)

    args = parser.parse_args()

    log_files = args.logfile if args.logfile else []
    if args.command == 'realtime' or args.command == 'listener':
        timestamp = datetime.datetime.now().strftime("error-report-%Y%m%d-%H%M%S")
        log_files.append((timestamp, 'ERROR'))
    configure_logger(console_level=args.loglevel, log_files=log_files)

    if args.config is not None:
        DrsLoader.set_drs_config_subdir(args.config)

    if args.command == 'realtime' or args.command == 'listener':
        queue = run_listener(args.port)
        load_and_start_realtime(args.processes, queue)
    else:
        loader = DrsLoader()
        cfht = loader.get_loaded_trigger_module()
        from cfht import CfhtDrsTrigger, CfhtDrsSteps, FileSelectionFilters

        if args.command == 'version':
            if args.drs:
                print(CfhtDrsTrigger.drs_version())
            elif args.trigger:
                print(CfhtDrsTrigger.trigger_version())
            else:
                print('DRS version', CfhtDrsTrigger.drs_version(), '-',
                      'Trigger version', CfhtDrsTrigger.trigger_version())
        else:
            reduce_execute(args, CfhtDrsTrigger, CfhtDrsSteps, FileSelectionFilters)
